spring:
  application:
    name: spring-reactive-stockapi

  data:
    mongodb:
      uri: mongodb://192.168.99.100:27017,192.168.99.100:27017
      database: shop
server:
 port: 8083
 
 # kafka
 
kafka:
  bootstrap-server: 192.168.99.100:29092
  acks: all
  retries: 2147483647  # retry=2147483647 = met nb de retry que peut effectuer
              # jsuque au time out(mieuxx vaut mettre cette conste)
  batch-size: 131072
  buffer-memory: 80000000
  client-id: producerEvent
  idempotence: true
  compression-type: snappy
  topic-name: stocksupp-v1
  user: producer-user
  password: producer-pwd

