spring:
  application:
    name: spring-rective-mongoapi

  data:
    mongodb:
      uri: mongodb://192.168.99.101:27017,192.168.99.101:27017 # localhost pblm liée à dockers 192.168.99.101 IP link with quickStart docker
      database: shop
#      server:
#        port: 8080
#      repositories:
#        enabled: true


#failover: mode qui permet de lister les server qui peuvent sse connecter à l'api mongodb
# server amberquer par la version de spring boot uitlisé au sein de se projet
#  C:\Users\guill\Documents\FormationJavaData\BIG_DATA_PROJET\microservices-data\microservices-api
#est un serveur Netty non tomcat

#server:
#  prot: 8082, 0: indique à spring qu'il peut séléctioner aléatoirement les port à utiliser
